[profile.default]
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 4500
out = 'dist/artifacts'
test = 'test'
src = 'src'
libs = ['lib']
gas_reports = ['*']

fs_permissions = [{ access = "read", path = "./addresses"}]
